### ISSUE TITLE
Обложка

### ISSUE THREAD

**Issue by vertexofvortex** [vertexofvortex/vertexofvortex.github.io#11]
"Начальный экран", где находится логотип, не адаптируется под всю высоту экрана.

**Comment by vertexofvortex** [comment]
Исправлено.
```css
html, body, cover-wrapper {
    height: 100%;
}
```
